<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PostSeeder extends Seeder
{
    public function run(): void
    {
        $now = now();

        // ===================== 5 bài viết blog (post_type = 'post') =====================
        $blogPosts = [
            [
                'topic_id'    => 1,
                'title'       => "Top 5 đồng hồ sang trọng năm 2025",
                'slug'        => "top-5-dong-ho-sang-trong-2025",
                'image'       => "luxury1.jpg",
                'content'     => "Khám phá những mẫu đồng hồ sang trọng hàng đầu năm 2025, từ các thương hiệu danh tiếng Thụy Sĩ.",
                'description' => "5 mẫu đồng hồ sang trọng không thể bỏ qua năm 2025.",
                'post_type'   => 'post',
                'created_by'  => 1,
                'status'      => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'topic_id'    => 1,
                'title'       => "Hướng dẫn chọn đồng hồ phù hợp với phong cách của bạn",
                'slug'        => "huong-dan-chon-dong-ho-phu-hop",
                'image'       => "luxury2.jpg",
                'content'     => "Chọn đồng hồ sang trọng phù hợp với trang phục, phong cách và tính cách cá nhân.",
                'description' => "Mẹo chọn đồng hồ sang trọng hợp phong cách cá nhân.",
                'post_type'   => 'post',
                'created_by'  => 1,
                'status'      => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'topic_id'    => 1,
                'title'       => "Các thương hiệu đồng hồ Thụy Sĩ nổi tiếng",
                'slug'        => "thuong-hieu-dong-ho-thuy-si-noi-tieng",
                'image'       => "luxury3.jpg",
                'content'     => "Tìm hiểu về các thương hiệu đồng hồ Thụy Sĩ nổi tiếng với thiết kế vượt thời gian.",
                'description' => "Danh sách thương hiệu đồng hồ Thụy Sĩ uy tín và sang trọng.",
                'post_type'   => 'post',
                'created_by'  => 1,
                'status'      => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'topic_id'    => 1,
                'title'       => "Cách bảo quản đồng hồ cơ sang trọng",
                'slug'        => "cach-bao-quan-dong-ho-co",
                'image'       => "luxury4.jpg",
                'content'     => "Bí quyết bảo quản đồng hồ cơ để luôn hoạt động chính xác và giữ vẻ đẹp sang trọng.",
                'description' => "Hướng dẫn bảo quản đồng hồ cơ cao cấp.",
                'post_type'   => 'post',
                'created_by'  => 1,
                'status'      => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'topic_id'    => 1,
                'title'       => "Xu hướng đồng hồ sang trọng 2025",
                'slug'        => "xu-huong-dong-ho-sang-trong-2025",
                'image'       => "luxury5.jpg",
                'content'     => "Các xu hướng thiết kế đồng hồ sang trọng năm 2025 từ chất liệu, màu sắc đến kiểu dáng.",
                'description' => "Những xu hướng đồng hồ sang trọng nổi bật năm 2025.",
                'post_type'   => 'post',
                'created_by'  => 1,
                'status'      => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
        ];

        // ===================== Bài viết cho menu footer (post_type = 'page') =====================
        $footerPages = [
            // === Về Chúng Tôi ===
            [
                'topic_id'    => null,
                'title'       => "Giới thiệu HoangWatch",
                'slug'        => "about-us",
                'image'       => "about-us.jpg",
                'content'     => "HoangWatch là thương hiệu đồng hồ sang trọng uy tín, cam kết chất lượng và dịch vụ khách hàng tuyệt vời.",
                'description' => "Tìm hiểu về HoangWatch.",
                'post_type'   => 'page',
                'created_by'  => 1,
                'status'      => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'topic_id'    => null,
                'title'       => "Địa chỉ & liên hệ",
                'slug'        => "contact-info",
                'image'       => "contact.jpg",
                'content'     => "Thông tin liên hệ và địa chỉ cửa hàng HoangWatch.",
                'description' => "Liên hệ với chúng tôi.",
                'post_type'   => 'page',
                'created_by'  => 1,
                'status'      => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'topic_id'    => null,
                'title'       => "Giờ làm việc",
                'slug'        => "working-hours",
                'image'       => "working-hours.jpg",
                'content'     => "Giờ làm việc của HoangWatch để khách hàng tiện tham khảo.",
                'description' => "Giờ mở cửa cửa hàng.",
                'post_type'   => 'page',
                'created_by'  => 1,
                'status'      => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],

            // === Chính Sách & Hướng Dẫn ===
            [
                'topic_id'    => null,
                'title'       => "Chính sách bảo mật",
                'slug'        => "privacy-policy",
                'image'       => "privacy.jpg",
                'content'     => "Chính sách bảo mật thông tin khách hàng tại HoangWatch.",
                'description' => "Bảo mật thông tin cá nhân của bạn.",
                'post_type'   => 'page',
                'created_by'  => 1,
                'status'      => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'topic_id'    => null,
                'title'       => "Điều khoản sử dụng",
                'slug'        => "terms-of-service",
                'image'       => "terms.jpg",
                'content'     => "Điều khoản sử dụng dịch vụ tại HoangWatch.",
                'description' => "Quy định sử dụng website và dịch vụ.",
                'post_type'   => 'page',
                'created_by'  => 1,
                'status'      => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'topic_id'    => null,
                'title'       => "Chính sách đổi trả",
                'slug'        => "return-policy",
                'image'       => "return.jpg",
                'content'     => "Chính sách đổi trả sản phẩm tại HoangWatch.",
                'description' => "Quy định đổi trả hàng hóa.",
                'post_type'   => 'page',
                'created_by'  => 1,
                'status'      => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'topic_id'    => null,
                'title'       => "Chính sách vận chuyển",
                'slug'        => "shipping-policy",
                'image'       => "shipping.jpg",
                'content'     => "Chính sách vận chuyển và giao hàng tại HoangWatch.",
                'description' => "Thông tin vận chuyển hàng hóa.",
                'post_type'   => 'page',
                'created_by'  => 1,
                'status'      => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'topic_id'    => null,
                'title'       => "Phương thức thanh toán",
                'slug'        => "payment-methods",
                'image'       => "payment.jpg",
                'content'     => "Các phương thức thanh toán tại HoangWatch.",
                'description' => "Thanh toán tiện lợi và an toàn.",
                'post_type'   => 'page',
                'created_by'  => 1,
                'status'      => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],

            // === Hỗ Trợ Khách Hàng ===
            [
                'topic_id'    => null,
                'title'       => "Câu hỏi thường gặp (FAQ)",
                'slug'        => "faq",
                'image'       => "faq.jpg",
                'content'     => "Các câu hỏi thường gặp về sản phẩm và dịch vụ HoangWatch.",
                'description' => "Hướng dẫn và giải đáp thắc mắc.",
                'post_type'   => 'page',
                'created_by'  => 1,
                'status'      => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'topic_id'    => null,
                'title'       => "Trung tâm hỗ trợ / khiếu nại",
                'slug'        => "support-center",
                'image'       => "support.jpg",
                'content'     => "Thông tin trung tâm hỗ trợ và xử lý khiếu nại tại HoangWatch.",
                'description' => "Hỗ trợ khách hàng và giải quyết khiếu nại.",
                'post_type'   => 'page',
                'created_by'  => 1,
                'status'      => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'topic_id'    => null,
                'title'       => "Hướng dẫn bảo hành",
                'slug'        => "warranty-guide",
                'image'       => "warranty.jpg",
                'content'     => "Hướng dẫn quy trình bảo hành đồng hồ tại HoangWatch.",
                'description' => "Thông tin bảo hành và dịch vụ hậu mãi.",
                'post_type'   => 'page',
                'created_by'  => 1,
                'status'      => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
            [
                'topic_id'    => null,
                'title'       => "Chat trực tuyến",
                'slug'        => "live-chat",
                'image'       => "live-chat.jpg",
                'content'     => "Kết nối trực tuyến với đội ngũ tư vấn khách hàng HoangWatch.",
                'description' => "Hỗ trợ trực tuyến nhanh chóng.",
                'post_type'   => 'page',
                'created_by'  => 1,
                'status'      => 1,
                'created_at'  => $now,
                'updated_at'  => $now,
            ],
        ];

        DB::table('posts')->insert(array_merge($blogPosts, $footerPages));
    }
}
